name: "TEI validation"
description: "Validate XML documents against TEI schema"
author: "Carsten Milling <cmil@hashtable.de>"

inputs:
  schema:
    description: "Schema to validate against"
    required: false
    default: "tei"
  version:
    description: "Schema version to validate against"
    required: false
    default: ""
  files:
    description: "Path or pattern to select TEI files"
    required: false
    default: "tei/*.xml"
  warn-only:
    description: "Exit gracefully when validation fails"
    required: false
    default: "false"

outputs:
  errors:
    description: "Number of errors"

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_SCHEMA: ${{ inputs.schema }}
    INPUT_VERSION: ${{ inputs.version }}
    INPUT_FILES: ${{ inputs.files }}
