name: "XML validation"
description: "Validate XML documents against Relax NG and Schematron schemas"
author: "Carsten Milling <cmil@hashtable.de>"

inputs:
  files:
    description: "Files to validate"
    required: true
    default: ""
  schema:
    description: "Schema to validate against"
    required: false
    default: "tei"
  version:
    description: "Schema version to validate against"
    required: false
    default: ""
  warn-only:
    description: "Exit gracefully when validation fails"
    required: false
    default: "false"

outputs:
  errors:
    description: "Number of errors"

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_SCHEMA: ${{ inputs.schema }}
    INPUT_VERSION: ${{ inputs.version }}
    INPUT_FILES: ${{ inputs.files }}
